### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase.

### ISSUE THREAD

**Issue by Techienaut** [turkenh/ansible-interactive-tutorial#3] opened 2017-10-24 23:58 UTC
OS: Xubuntu 17.04
Docker version: 17.09.0-ce, build afdb6d4 API 1.32

Everything seem fine at first. but at the end given the error and unable to run tutorial: 
`docker: invalid reference format: repository name must be lowercase.`

I had to sudo, since docker doesn't run w/o elevated permissions.

sudo ./tutorial.sh
creating network ansible.tutorial
starting container host0.example.org: mapping hostport 42726 -> container port 80 && hostport 42729 -> container port 8080
Unable to find image 'turkenh/ubuntu-1604-ansible-docker-host:1.0' locally
1.0: Pulling from turkenh/ubuntu-1604-ansible-docker-host
d5c6f90da05d: Pulling fs layer
bbbe761fcb56: Pulling fs layer
7afa5ede606f: Pulling fs layer
f6b7253b56f4: Pulling fs layer
2b8db33536d4: Pulling fs layer
a2b45d4ab2fd: Pulling fs layer
03b1c7fa7980: Pulling fs layer
10a4ee0fd8bb: Pulling fs layer
ad81eaefa5af: Pulling fs layer
751338e06da3: Pulling fs layer
03b1c7fa7980: Waiting
a2b45d4ab2fd: Waiting
10a4ee0fd8bb: Waiting
ad81eaefa5af: Waiting
751338e06da3: Waiting
2b8db33536d4: Waiting
f6b7253b56f4: Waiting
7afa5ede606f: Download complete
bbbe761fcb56: Verifying Checksum
bbbe761fcb56: Download complete
f6b7253b56f4: Verifying Checksum
f6b7253b56f4: Download complete
2b8db33536d4: Download complete
03b1c7fa7980: Download complete
10a4ee0fd8bb: Verifying Checksum
10a4ee0fd8bb: Download complete
ad81eaefa5af: Download complete
751338e06da3: Download complete
d5c6f90da05d: Verifying Checksum
d5c6f90da05d: Download complete
d5c6f90da05d: Pull complete
bbbe761fcb56: Pull complete
7afa5ede606f: Pull complete
f6b7253b56f4: Pull complete
2b8db33536d4: Pull complete
a2b45d4ab2fd: Retrying in 5 seconds
a2b45d4ab2fd: Retrying in 4 seconds
a2b45d4ab2fd: Retrying in 3 seconds
a2b45d4ab2fd: Retrying in 2 seconds
a2b45d4ab2fd: Retrying in 1 second
a2b45d4ab2fd: Download complete
a2b45d4ab2fd: Pull complete
03b1c7fa7980: Pull complete
10a4ee0fd8bb: Pull complete
ad81eaefa5af: Pull complete
751338e06da3: Pull complete
Digest: sha256:84c1c22800da13f28a2a11ad3efc1d208a3c90bcd5b9687eb3ca44ebb449188f
Status: Downloaded newer image for turkenh/ubuntu-1604-ansible-docker-host:1.0
starting container host1.example.org: mapping hostport 42727 -> container port 80 && hostport 42730 -> container port 30000
starting container host2.example.org: mapping hostport 42728 -> container port 80 && hostport 42731 -> container port 443
starting container ansible.tutorial
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

**Comment by turkenh** [comment] 2017-10-26 19:59
I could not reproduce with exactly same OS and docker version. 

But I could reproduce with a directory name including spaces, i.e.

`~/LEARN ANSIBLE/ansible-interactive-tutorial# ./tutorial.sh`

Can you please share fullpath of your working directory? Is it the case for you?

I will provide a fix for this

**Closed as completed** 2017-10-26 20:02 UTC

**Comment by Techienaut** [comment] 2017-11-02 04:25
It works! Ty. Nice job :1st_place_medal: 
And it works for spaces.
My path is /home/vagrant/Downloads/to_delete/BLAH blah/ansible-interactive-tutorial
